---
- hosts: localhost
  connection: local
  become: true

roles:
  - role: 'plays/roles/rust.yml'
  #tasks:
  #  - import_tasks: plays/core.yml
  #  - import_tasks: plays/software/alacritty.yml
  #  - import_tasks: plays/software/spotify.yml
  #  - import_tasks: plays/software/bitwarden.yml
  #  - import_tasks: plays/wallpaper.yml





  

  
  

