---
- name: Install vim
  package:
    name: vim
    state: present

- name: Install tmux
  package:
    name: tmux
    state: present

- name: Install Flatpak
  package:
    name: flatpak
    state: present

# Get the software
- import_tasks: software/spotify
- import_tasks: software/bitwarden

#- name: Fix Flatpack remotes
#  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
