---
- name: Install pip
  package:
    name: pip
    state: present

- name: Install vim
  package:
    name: vim
    state: present

- name: Install tmux
  package:
    name: tmux
    state: present

- name: Install Code
  package:
    name: code
    state: present

- name: Install VLC
  package:
    name: vlc
    state: present

- name: Install Flatpak
  package:
    name: flatpak
    state: present


- name: Fix Flatpack remotes
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Get the software
- import_tasks: playbooks/software/spotify
- import_tasks: playbooks/software/bitwarden.yml
- import_tasks: playbooks/software/teams.yml
- import_tasks: playbooks/software/outlook.yml