- name: Install Deps Alacritty
  apt:
    name: 
    - cmake 
    - pkg-config 
    - libfreetype6-dev 
    - libfontconfig1-dev 
    - libxcb-xfixes0-dev 
    - libxkbcommon-dev 
    - python3 

- name: Get alacritty
  git:
    repo: https://github.com/alacritty/alacritty.git 
    dest: /tmp/alacritty

- name: compile allacritty
  shell: cd /tmp/alacritty  && cargo build --release && cd ..

  