---
- hosts: localhost
  connection: local
  become: true

tasks:
  - name: copy .tmux.conf file
    copy:
     src: files/tmux.conf
     dest: /home/tldart/.tmux.conf
     owner: tldart
     group: tldart

  - name: copy .vimrc file
    copy:
     src: files/vimrc
     dest: /home/tldart/.vimrc
     owner: tldart
     group: tldart

  - name: copy .zshrc file
    copy:
     src: files/zshrc
     dest: /home/tldart/.zshrc
     owner: tldart
     group: tldart

  - name: copy .alacritty file
    copy:
     src: files/alacrity.toml
     dest: /home/tldart/.alacritty.toml
     owner: tldart
     group: tldart